### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by splitbrain**
This fixes the tests and adds fixes for the original issues 12 (missing IPv6 support) and 15 (optionally allow local addresses).

### CODE REVIEW

**Comment by aziraphale** [comment]
Looks good to me, thanks for this :)

**Comment by splitbrain** [comment]
Thanks for merging. Can you update the version tag for composer?

**Comment by aziraphale** [comment]
Good point - done!

**Comment by splitbrain** [comment]
Hmm https://packagist.org/packages/aziraphale/email-address-validator still shows it at 2.0.0 from 2015?

**Comment by aziraphale** [comment]
Sorry about the delay. I could't find a way to create a tag directly on github and I didn't have this repo checked out anywhere obvious. It's been a long time since I last had to publish anything to Packagist so I forgot about the tagging part :) Should be sorted now though.

**Pull request merged**
